### ISSUE TITLE
the width of the button has a problem

### ISSUE THREAD

**Issue by jackpaster** [abakhtin/ABProgressButton#1]
When you put the button in a view controller, the button has a fixed width, you can't constraint the button to the leading and trailing sides of the view controller. The reason I need this is for different screen sizes and being able to fit the button for small and big screen sizes from the iPhone 5 to the iPhone 6. I'm hoping you can help me with this width problem.

**Comment by jackpaster** [comment]
If you don't understand what I'm trying to say then I could just send you pictures

**Comment by abakhtin** [comment]
hi @jackpaster 
check last commit for changes please.
I fixed layer path after relayout issue. New example works perfect.
Thank you for reply.
