### ISSUE TITLE
Important center animation shift

### ISSUE THREAD

**Issue by jackpaster** [abakhtin/ABProgressButton#3]
Hey this is jack, 

first of all, i love the work you do on github. Major props. But I need your help. can you add a float function in the abprogressbutton swift file that would change the center of the of the progress animation. That would allow me to shift the animation to the left or right in the main.storyboard. Thanks and i hope to hear back from you.

**Comment by abakhtin** [comment]
hi,
sorry, what do you mean by "that would change the center of the progress animation"?

**Comment by jackpaster** [comment]
I have a button but it has to be big enough to allow the user to tap and
for the button to respond. I want to offset the animating circle to the
left or right move the progress animation a couple of values or points from
its center position. The animating circle is constrained to the bounds and
center of the button. How can you offset the animation rotating circle
animation. Can you please help ofset it

**Comment by jackpaster** [comment]
@abakhtin I have a button but it has to be big enough to allow the user to tap and for the button to respond. I want to offset the animating circle to the left or right move the progress animation a couple of values or points from its center position. The animating circle is constrained to the bounds and center of the button. How can you offset the animation rotating circle animation. Can you please help ofset it
